"""updated owner again

Revision ID: 01e9ca00cc92
Revises: 5c439813d532
Create Date: 2024-05-07 19:13:19.041648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e9ca00cc92'
down_revision = '5c439813d532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_squads_owner_users'), 'users', ['owner'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_squads_owner_users'), type_='foreignkey')

    # ### end Alembic commands ###
