"""updated owner info

Revision ID: 5c439813d532
Revises: f97cf355a485
Create Date: 2024-05-07 19:04:51.953741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c439813d532'
down_revision = 'f97cf355a485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_squads_owner_users', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_squads_owner_users', 'users', ['owner'], ['id'])

    # ### end Alembic commands ###
