"""adding liked column to squadusers table

Revision ID: c180046911d8
Revises: fb516c9d4f98
Create Date: 2024-03-30 18:30:18.010840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c180046911d8'
down_revision = 'fb516c9d4f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squadusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squadusers', schema=None) as batch_op:
        batch_op.drop_column('liked')

    # ### end Alembic commands ###
