"""changed table for many-to-many

Revision ID: f00f56f6a659
Revises: 5ef2caa13cd5
Create Date: 2024-03-30 09:01:13.493467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00f56f6a659'
down_revision = '5ef2caa13cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squadusers')
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_squads_owner_user_id_users', type_='foreignkey')
        batch_op.drop_column('owner_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_squads_owner_user_id_users', 'users', ['owner_user_id'], ['id'])

    op.create_table('squadusers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('squad_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name='fk_squadusers_squad_id_squads'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_squadusers_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_squadusers')
    )
    # ### end Alembic commands ###
