"""altered tables back and added seed data

Revision ID: fb516c9d4f98
Revises: f00f56f6a659
Create Date: 2024-03-30 09:35:50.594494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb516c9d4f98'
down_revision = 'f00f56f6a659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squadusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squadusers_squad_id_squads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_squadusers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squadusers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squadusers')
    # ### end Alembic commands ###
